---

- name: base (root)
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - include_tasks: plays/yum_pkgs_base.yml
    - include_tasks: plays/awscli.yml
    - include_tasks: plays/docker.yml
    - include_tasks: plays/virtualization.yml
    - include_tasks: plays/pyenv_deps.yml

- name: base (davido)
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: davido
  tasks:
    - include_tasks: plays/flatpak_pkgs_base.yml
    - include_tasks: plays/starship.yml
    - include_tasks: plays/pyenv.yml
    - include_tasks: plays/vscode.yml
    - include_tasks: plays/ssh.yml
    - include_tasks: plays/tfenv.yml
    - include_tasks: plays/fish.yml
    - include_tasks: plays/gnome.yml
